import type { Metadata } from 'next'
import { getCssText, globalStyles } from '@/styles'
import { Saira } from 'next/font/google'
import { VideoProvider } from '@/contexts'

const saira = Saira({ subsets: ['latin'] })

globalStyles()

export const metadata: Metadata = {
  title: 'Apollo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={saira.className}>
        <VideoProvider>{children}</VideoProvider>
      </body>
    </html>
  )
}
